### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by RockinRoel** [CamHenlin/TouchPolyfill#11]
Hi, I'm looking to use this polyfill, or base my own implementation on this for a project, but there is no license file. I was wondering under which terms you are making this polyfill available?

**Comment by CamHenlin** [comment]
Hi Roel,

Sorry about that! I will put an MIT license on that repo later if that works for you. Let me know if some other license would suit your new project better 

Thanks
Cameron

**Comment by CamHenlin** [comment]
Just added it. Again, let me know if you would like a different license for your own personal use

**Comment by RockinRoel** [comment]
MIT license is fine, thanks. However, the file appears to be empty?

**Comment by CamHenlin** [comment]
Oops, fixed :)
