### ISSUE TITLE
Demo link broken

### ISSUE THREAD

**Issue by ljani** [CamHenlin/TouchPolyfill#12]
It seems that the demo link [`http://henlin.org/touchpolyfill/demo.html`](http://henlin.org/touchpolyfill/demo.html) mentioned in the [`README.md`](https://github.com/CamHenlin/TouchPolyfill/blob/756521c1cb73c72a57cfb92ef152eee1a6225ef1/README.md) is broken: `404 Not Found`.

**Comment by CamHenlin** [comment]
Fixed, thank you
